name: terraform-and-security-checks
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  fmt-validate-checkov-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        run: terraform -chdir=terraform fmt -check
      - name: Terraform validate
        run: terraform -chdir=terraform validate
      - name: Checkov (IaC scan)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: terraform
      - name: Gitleaks (secrets scan)
        uses: gitleaks/gitleaks-action@v2